server:
  port: 5000
  servlet:
    context-path: /auth
    
spring:
  application:
    name: auth-server
  profiles:
    active: dev
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        namespace: 24384506-b2bf-4fbe-a9cb-986c4911fac0
#      config:
#        server-addr: localhost:8848
#        file-extension: yml
#        shared-dataids: application-redis,authorization-server
