server:
  port: 8085
  contextPath: /user
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#spring:
#  application:
#    name: eureka-client-01

security:
  oauth2:
    client:
      client-id: user
      client-secret: 123456
      user-authorization-uri: http://localhost:8083/sso-auth/oauth/authorize
      access-token-uri: http://localhost:8083/sso-auth/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:8083/sso-auth/oauth/token_key
