server:
  port: 8888
  contextPath: /
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#spring:
#  application:
#    name: eureka-client-01

zuul:
  routes:
    user: /users/**
